### ISSUE TITLE
Uniqueness validator doesn't work on update

### ISSUE THREAD

**Issue by rubydev** [DavyJonesLocker/client_side_validations-mongoid#12]
client_side_validations: 4.2.4
client_side_validations-mongoid: 5.1.0
client_side_validations-simple_form: 3.2.3
rails 4.2.6
mongoid: 5.1.3
mongo: 2.2.5

model: 
<pre>
class TicketInstruction
  include Mongoid::Document

  field :name, type: String
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end
</pre>

See this request:
<img width="748" alt="request" src="https://cloud.githubusercontent.com/assets/599358/16377910/1e7f9cd8-3c69-11e6-86be-6de636d86b9b.png">
is id[$oid] parameter correct? Or it should be without $oid?

Javascript code:
<pre>
if(window.ClientSideValidations===undefined)window.ClientSideValidations={};window.ClientSideValidations.disabled_validators=[];window.ClientSideValidations.number_format={"separator":".","delimiter":","};if(window.ClientSideValidations.patterns===undefined)window.ClientSideValidations.patterns = {};window.ClientSideValidations.patterns.numericality=/^(-|\+)?(?:\d+|\d{1,3}(?:\,\d{3})+)(?:\.\d*)?$/;if(window.ClientSideValidations.forms===undefined)window.ClientSideValidations.forms={};window.ClientSideValidations.forms['edit_ticket_instruction_52ab5d56f7bd9125c100000b'] = {"type":"SimpleForm::FormBuilder","error_class":"help-block","error_tag":"span","wrapper_error_class":"has-error","wrapper_tag":"div","wrapper_class":"form-group","wrapper":"horizontal_form","validators":{"ticket_instruction[name]":{"presence":[{"message":"can't be blank"}],"uniqueness":[{"message":"is already taken","case_sensitive":false,"id":{"$oid":"52ab5d56f7bd9125c100000b"}}]},"ticket_instruction[description]":{"presence":[{"message":"can't be blank"}]}}};
</pre>

I can't update object, because object with same name already exists, but it's the same object. By me in param should be only "id", not "id[$oid]"?

<pre>
TicketInstruction.count
=> 52

TicketInstruction.first
=> #&ltTicketInstruction _id: 528e32b5f7bd91afd7000031, name: "Student Agency" .... &gt

TicketInstruction.where(_id: { '$ne' => {"$oid":"528e32b5f7bd91afd7000031"} }).count
=> 52

TicketInstruction.where(_id: { '$ne' => "528e32b5f7bd91afd7000031" }).count
=> 51
</pre>

Edit: id[$oid] was in parameter always, so problem is somewhere else..

**Comment by rubydev** [comment]
Sorry, my fault.

**Comment by tagliala** [comment]
glad you solved. I was giving a look at the specs
